### ISSUE TITLE
Lost processed images

### ISSUE THREAD

**Issue by schraivo** [embl-cba/bd-cellview#21]
Hi @tischi ,

I have observed sth weird with a recent dataset. When starting processing on Slurm, everything seems to be running fine (as shown in the Fiji log file), but there's no data ending up in the experiment folder (and there's no new folder generated for the JPEGs). I attached the corresponding batch processing file and /cba/cluster/schraivo folder. Any idea what could have gone wrong? I tried already twice (and started the job again half an hour ago). 

The only difference to what I've done so far is the significantly larger size of the dataset (i.e. much more images). Could that be a reason?

Best and thanks,

Daniel

[Archive.zip](https://github.com/tischi/fccf/files/5796623/Archive.zip)

**Comment by gabrielpan147** [comment]
Hello, I also met this issue this day. Everything seemed to work fine when I tried it locally but there were no output folders. I would like to ask if you think it is a memory related issue since I only have 8GB for my local machine? Or maybe it is due to I put a subfolder under the image folder? 

It is weird as I can perfectly run the random preview function, but can not batch process even 5 images..

**Comment by gabrielpan147** [comment]
I just checked the folder, the processed images are not disappeared but they are not in the correct folder. They were put under the same folder with the original images.

**Comment by tischi** [comment]
@gabrielpan147 

Clicking `Batch process images of selected gate from all tables` results in a new folder:

<img width="354" alt="image" src="https://github.com/embl-cba/bd-cellview/assets/2157566/3f5ff85b-e956-4227-82c6-a18880e86561">

The location of the root of this folder cannot be freely chosen, but is the `experimentDirectory`, which is  folders up from the table file:

`experimentDirectory = new File( selectedTableFile.getParent() ).getParent();`

@schraivo otherwise, can we close this issue? I know the cluster processing is not working right now, but this is mentioned in another issue.

**Comment by gabrielpan147** [comment]
> @gabrielpan147
> 
> Clicking `Batch process images of selected gate from all tables` results in a new folder:
> 
> <img alt="image" width="354" src="https://private-user-images.githubusercontent.com/2157566/294899619-3f5ff85b-e956-4227-82c6-a18880e86561.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3Njg4MjAsIm5iZiI6MTcwNDc2ODUyMCwicGF0aCI6Ii8yMTU3NTY2LzI5NDg5OTYxOS0zZjVmZjg1Yi1lOTU2LTQyMjctODJjNi1hMTg4ODBlODY1NjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDlUMDI0ODM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjI0NzA0N2NkMDkzMWNhOWJjMDY1MDExMTg3NzY4NzgzMmVmODg4ZmYzYTRjYTY2OTQ0ZTQwYTA3M2MxOGVhMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.O_vfRY9JW26ewpwopCFU-Tw4bDl0FSZiCe9wFhzuuSA">
> The location of the root of this folder cannot be freely chosen, but is the `experimentDirectory`, which is folders up from the table file:
> 
> `experimentDirectory = new File( selectedTableFile.getParent() ).getParent();`
> 
> @schraivo otherwise, can we close this issue? I know the cluster processing is not working right now, but this is mentioned in another issue.

Hello Tischi,

Yes it works on my demo dataset with around 10 images, a new folder is generated and .jpg files are moved there. However, when I processed another dataset with around 10,000 images, the .jpg images are created but under the original image folder. IN the case, the "image" folder. I don't know Java so I did not go through the source code to check. Afterall, it is good to use. Thank you!!

**Comment by tischi** [comment]
@gabrielpan147 this is strange. I don't see why this would happen.
